### ISSUE TITLE
What is the version number of imageio? Thank you very much~

### ISSUE THREAD

**Issue by 805094591** [zhengkw18/face-vid2vid#8]

**Comment by zhengkw18** [comment]
Any stable version of imageio for python>=3.7 should be ok

**Comment by 805094591** [comment]
Could you upload a requirments.yml, which include all the installed requirments and is deduced from anaconda for this project, please? Thank you very much~

**Comment by zhengkw18** [comment]
Sorry, currently I do not have such an environment in my hand. I think you can choose any python>=3.7, and install the following packages without specifying the version
```
numpy
pillow
torch
torchvision
scikit-image
scikit-learn
imageio
pandas
```

**Comment by 805094591** [comment]
(face-vid2vid) F:\github\face-vid2vid>python evaluate.py --ckp=100 --source=out/a.jpg --driving=out
Traceback (most recent call last):
  File "evaluate.py", line 109, in <module>
    eval(args)
  File "G:\Conda_data\envs\face-vid2vid\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "evaluate.py", line 78, in eval
    video_array = [img_as_float32(io.imread(os.path.join(args.driving, frames[idx]))) for idx in range(num_frames)]
  File "evaluate.py", line 78, in <listcomp>
    video_array = [img_as_float32(io.imread(os.path.join(args.driving, frames[idx]))) for idx in range(num_frames)]
  File "G:\Conda_data\envs\face-vid2vid\lib\site-packages\skimage\io\_io.py", line 53, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "G:\Conda_data\envs\face-vid2vid\lib\site-packages\skimage\io\manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)
  File "G:\Conda_data\envs\face-vid2vid\lib\site-packages\skimage\io\_plugins\imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "G:\Conda_data\envs\face-vid2vid\lib\site-packages\imageio\core\functions.py", line 159, in imread
    with imopen(uri, "ri", plugin=format) as file:
  File "G:\Conda_data\envs\face-vid2vid\lib\site-packages\imageio\core\imopen.py", line 277, in imopen
    raise err_type(err_msg)
ValueError: Could not find a backend to open `out\a.mp4`` with iomode `ri`.

**Comment by 805094591** [comment]
I do not know the reason of that phenomenon~

**Comment by zhengkw18** [comment]
You should notice that `driving` is a folder containing frames of video, not a video.

**Comment by 805094591** [comment]
The project runs well due to your help~ Your explanation helped me solve the problem that bothered me for a long time ~ Thank you very much～
